default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
 <<: *default
 database: LegitNews-dev
 host: db
 username: postgres
 password:

test:
 <<: *default
 host: <%=ENV['POSTGRES_HOST'] ||= 'db' %>
 username: <%=ENV['POSTGRES_USER'] ||= 'postgres' %>
 password: <%=ENV['POSTGRES_PASSWORD'] ||= '' %>
 database: LegitNews-test

production:
 <<: *default
 database: LegitNews
 username: LegitNews
 password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
